### ISSUE TITLE
Problem with reading RHT03 sensor

### ISSUE THREAD

**Issue by Kytrix** [electricimp/reference#29]
Hi,
I'm using a Electric Imp with this firmware version: 138d21b - release-30.22 - Fri Oct 17 12:15:01 2014

but the code doesn't working for me with my RHT03 sensor purchased here : https://www.sparkfun.com/products/10167

**1. The 10k resistor is too big**
 Here is the signal view on pin 2 of the Sensor (or pin 2 of the Imp)
![10k-resistor](https://cloud.githubusercontent.com/assets/3098540/5063285/598de89c-6de0-11e4-91ee-80ef14dbadf5.png)
as you can see the level hight is good (near 3.3v from ground : the little cyan triangle on the left and right side) but the low level, grounded by the pin 7 of the Imp through the resistor is too high ! (near 2v !)
now with a 1.3k Ohm resistor : 
![1 3k-resistor](https://cloud.githubusercontent.com/assets/3098540/5063295/ff8f321e-6de0-11e4-8d57-5ca6e7e499ff.png)
the low level is now below 1v ! much better.

**2. the first time, the down time is too long**
In the device code, the data acquisition is only called one time. because it happend just at boot (or other else) the first STARTTIME_LOW takes longer thant 1ms : 
![first-time-lowtimestart](https://cloud.githubusercontent.com/assets/3098540/5063309/7e17c178-6de1-11e4-953d-29792b1a86b0.png)
here it takes 42ms and the sensor didn't "get this as a start".
What I did is to put the read part inside a function and calling it in a loop (and I realy want to update the reading after few seconds)
```
function run()
{
    data <- dht22.read();
    server.log(format("Relative Humidity: %0.1f",data.rh)+" %");
    server.log(format("Temperature: %0.1f C",data.temp));
    
    // Once the table is constructed, send it out to the agent with "impValues"
    // as the identifier.
    agent.send("sensor", data);
    //ask a new read in 10s.
    imp.wakeup(10, run);
}
```
so the first read is still crap, but the others are okay !
![loop-read](https://cloud.githubusercontent.com/assets/3098540/5063329/57341b3c-6de2-11e4-9737-faef85bd6f7e.png)
now I get the 1ms STARTTIME_LOW and the sensor reply !

**3 the timmings need to me changed.**
here is a screenshot of my log with the hightime for each data:
![timmings](https://cloud.githubusercontent.com/assets/3098540/5063335/aeacd9d0-6de2-11e4-888d-accbf1b10ff7.png)
so my first hightime is 30ms instead of 20, so not reconized as a the STARTTIME_HIGH
and the the times for ZERO are between 25 and 27ms and the ONE times are between 73 and 74ms
so I change the timings as follow:
```
    static ZERO = 0.000030; // 26 us high for "0"
    static ONE = 0.000075; // 70 us high for "1"
```
I didn't change the frequency, but maybe we can play with it.

after this last modification it works like a charm !

Regards.
Kytrix.

**Comment by jp-stewart** [comment]
Kytrix, Did you ever post your modifications as a pull request?

I HAD a DHT11 (and found it to be terribly inaccurate) and it worked great with this code / no modification.

I upgraded to a RHT03 and then experienced the same issues you mention. However, I played with the settings until I was reliably able to get the code to work, but I had to make several changes. (I wish I had checked for your post first, heh.) I found slightly different settings to be reliable (through trial and error only). But maybe these devices are all slightly different?

static STARTTIME_LOW     = 0.009000;    // 9 ms low time for start
static ZERO              = 0.000027; // 27 us high for "0"
static ONE               = 0.000076;  // 76 us high for "1"    

I also had to change the humidity and temperature calculations (from the datasheet) as well.

humid = ((result[0] * 256.0) + result[1]) / 10.0;
temp = ((result[2] * 256.0) + result[3]) / 10.0;

Did you make these same changes?
J.P.
