### ISSUE TITLE
DHT22 accuracy

### ISSUE THREAD

**Issue by ArthurGuy** [electricimp/reference#37]
Hi,
I have just replaced two sensors from a home made arduino setup to electric imps, this is basically your DHT22 example.
The problem is the temperature readings are now about 3 or 4 degrees higher than they were before.

Has the code been verified or could some kind of inaccuracy be present in the system?

**Comment by ArthurGuy** [comment]
I have checked the temperature alongside a known reading and they are definitely 3.5 to 4.5 degrees out.
I am seeing this across two devices and two imps so I don't think it's a hardware problem.

**Comment by beardedinventor** [comment]
It doesn't look like we have any DHT22's kicking around to test with, but we'll take a look when we get some in stock.

In the meantime, if you find what's wrong with the code, feel free to submit a PR :)

**Comment by ArthurGuy** [comment]
After looking at the datasheet and the way another library implemented the code I couldn't find anything wrong, I think I just have a bad batch of sensors :disappointed:
